### ISSUE TITLE
Can we support hjkl?

### ISSUE THREAD

**Issue by yujunhui** [taylorconor/quinesnake#8]
Can we use the hjkl in vim to move the snake?

**Comment by pocc** [comment]
The author is hostile to the idea of changing keybindings (See issue #1), even when PRs submitted.

**Comment by taylorconor** [comment]
I'm not being hostile about it, there's just no reason to switch from one keybinding to another equally arbitrary keybinding. And supporting multiple keybindings is not part of the scope of this project since it's intended to be extremely minified code.

Supporting multiple keybindings in separate files distracts from the point of this program, which is to be an interesting hack project, not a particularly fun/playable game.

**Comment by pocc** [comment]
That's fine - just add a **Note:** in the `How to run it` section of your README. This sentence you wrote

Supporting multiple keybindings is not part of the scope of this project since it's intended to be extremely minified code.

is perfect.
